version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dpg-cc7e9d9a6gdvc1qkjno0-a
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: nn_chat_db_user
      POSTGRES_PASSWORD: process.env.DB_PASS
      POSTGRES_DB: nn_chat_db
      TZ: "Asia/Tokyo"
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data