version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: nn_chat_db
      POSTGRES_HOSTNAME: ${DATABASE_HOSTNAME}
      TZ: "Asia/Tokyo"
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data